### ISSUE TITLE
question: best approach for validations

### ISSUE THREAD

**Issue by jgamedev** [Semantic-Org/Semantic-UI-Ember#105]
Hi, can someone point me to an example of what the best approach is to integrate form validations (with visual  feedback for the user)  when using this library. I'm new to Ember so thank you for any help.

**Comment by aaronbhansen** [comment]
We use [Ember CP Validations](https://github.com/offirgolan/ember-cp-validations) in our own projects. Since so much of Ember is usually data bound, we use that instead of Semantic-UI's validations. 

We have a helper component we use that I created a gist for https://gist.github.com/aaronbhansen/f12dca7fdb5d81db7ad98bce44e641b3.

Then you can do something like this in your controller or component

```
actions: {
   save() {
      this.set('submitted', true);
      if (this.get('modelName.validations.isInvalid')) { return; }
```

```
{{#ui-field model=modelName property="description" submitted=submitted}}
    <label>Description</label>
    <div class="ui input>
      {{input value=modalName.description}}
   </div>
{{/ui-field}}
```

Hopefully that gives you an idea and a direction to go.
