### ISSUE TITLE
Custom AJAX function in search

### ISSUE THREAD

**Issue by denchen** [Semantic-Org/Semantic-UI-Ember#117]
I'm at a bit of a loss here. How would I create a custom ajax call for the `{{ui-search}}` component? Two reasons I need this: 1) depending on a selection elsewhere on my page, the search box behaves differently (different parameters for the search URL), and 2), before the actual search call, I need to make a request for a token and add it to the HTTP header. So I'd rather handle the entire part of making an ajax call (and parsing the response) rather than rely on Semantic UI to do so. I was looking at [Using Custom Backends](http://semantic-ui.com/behaviors/api.html#using-custom-backends), and it seems like this *may* be what I need. Is it possible to use `responseAsync` with `{{ui-search}}`?

**Comment by aaronbhansen** [comment]
To be honest, I haven't looked at the API backend too much from semantic, because I had to re-implement the api connection from what I already had in Ember Data. I did at one point override some of the methods on the dropdown and create a custom search using ember data. Here is the gist for it, it might help.

https://gist.github.com/aaronbhansen/83561cc2e5eb79dc2f86fae4b57e574a

For me at least, it was easier to use ember. You should be able to take these ideas and apply them to search. There are a few addons I'm using, ember concurrency, and composable helpers in the gist.

**Comment by villander** [comment]
@denchen  you can extend this component like this:

import SemanticUI from 'semantic-ui/components/ui-search';
export default SemanticUI.extend({
    // your stuff here, ajax, whathever 
  }
});
