### ISSUE TITLE
Checkbox's 'checked' no longer mutable?

### ISSUE THREAD

**Issue by jfarlow** [Semantic-Org/Semantic-UI-Ember#124]
After upgrading to the recent beta, the checkbox no longer seems to activate its checked variable properly.  The variable assigned to 'checked' seems somehow no longer mutable.

```
{{ui-checkbox checked=checkTest label="test" onChange=(action 'toggleCheck')}}
{{checkTest}} <---- always a static value, even when the checkbox is triggered (and is visually toggled from true/false).

```
If:
`export default Ember.Controller.extend({checkTest: true}`
Then the checkbox will be rendered properly, as true, but will still not update when a user checks the checkbox.

**Comment by aaronbhansen** [comment]
Are you updating checkTest to false in the toggleCheck action?

**Comment by jfarlow** [comment]
No.  In previous versions, and with ember checkboxes, having the property bound to the 'checked' property would bind both ways.  An update to the 'checked' property would update the bound value as well.  That no longer appears to be the case.

**Comment by aaronbhansen** [comment]
That makes sense, I'll need to think about it. The assumption on the DDAU branch was your data coming down into the component was the source of truth and the state on the component. The actions up sent notification that something happened to respond outside the component. 

If checked stays true, then I we have to look at having an internal state that is now different from the initial render / variables passed in. That also means we don't trigger an attrsUpdated event within Ember to correctly handle the new state within the component. 

There are two situations that conflict. 

One is someone clicks the checkbox, but for whatever reason, you don't want to mark the checked state as true, so you can choose to ignore it in your onChange action. So the checkbox doesn't change. This was the approach taken today, data always represents the state.

The other is what you're describing. Where you passed in an initial value, but want it to change even if the initial value doesn't update. 

I don't know if there is a clean way to have both approaches. I still feel like the first approach is correct and you should be updating the data to match the state you want. Otherwise you have a checkbox that acts independently of the data.

**Comment by jfarlow** [comment]
I think you're right, there are two issues that cannot be reconciled if the value is not bound in both directions:

If you do wish to intercept the action prior to making the change, that becomes difficult if the value is directly bound, like you state.

However, the data does *not* seem to be the source of truth right now the way the checkbox is wired. There is now the situation where the user is shown a non-truthful state of the variable.  That seems seems dangerous.  Currently it's possible for the value to be 'true', but the user sees false. Because they can change the component's state, without changing the bound variable's state.

Is there a way to force an error if the onChange is not used?  Or to monitor internally the state of isChecked, and to ensure that it matches its bound value?

I wouldn't see much of a problem if during the check event it went back to ask for the true state from the bound variable - and in the case above the checkbox would just do nothing when clicked, as the underlying value wasn't set up to change.

**Comment by aaronbhansen** [comment]
I think I understand what you're saying. Let me reiterate to be sure, then we can add a test for it.

- The checkbox starts off as true
- The user clicks the checkbox
- The onChange action is fired, but the checked value is ignored, and the checkbox should still be true
- Semantic-UI checkbox though shows it as being uncheck at the moment. The checked of true isn't representing the display value

This correct?

**Comment by jfarlow** [comment]
Exactly.  Where the initial state can be either true or false.

So when an onChange doesn't call for the checkbox's state: 

Solution 1: checkbox's visual state should not change because there was no change to the truthful data.

Solution 2: checkbox should itself affect the truthful data to mirror the user's action.  (old way, and how HTML5, and ember-chekboxs currently work)

Current state: checkbox (visual state) toggles as user indicated, but if no change is properly hooked up, the visual state can become detached from the truthful data.

**Comment by aaronbhansen** [comment]
Code wise, I think there are two ways to properly handle refusing a click on checkbox, without getting into the ember run queue to do a check later in time. (Using the run queue feels more like a hack to check back to see if values changed when they didn't).

**Option 1 (easiest, but could lead to possible issues):**
Since we are using composable actions instead of just action events, we could look for a return value of false to indicate that you want to cancel the current onChange event.

```
actions: {
    checkboxChanged(checked) {
       if (someCondititionNotTrue) {
         return false; // revert change
      }
     // otherwise updated binded value and things work as normal
    }
```

This isn't implemented today, it would need to be added. The reason I say it could lead to some possible issues is because of the old ember action events bubbling and returning false to stop bubbling. Not a huge risk, but I figure i'll get bug tickets for it.

**Option 2 (more specific):**
Using the last parameter that is appended into all semantic ui callbacks. It is the actual component that did the callback. You could in the code itself specify you don't want to check it.

```
actions: {
    checkboxChanged(checked, checkboxComponent) {
       if (someCondititionNotTrue) {
         return checkboxComponent.execute('set unchecked');
      }
     // otherwise updated binded value and things work as normal
    }
```

I'll need wait for more feedback from others upgrading to get a feel for which option is the best way to go when you want to do something thats not the expected result. 

The other goal of 2.0 release was exposing more internals of semantic-ui when you wanted to do something advanced. That way your codebase has total control over what happens and less logic is trying to be wrapped into the semantic-ui-ember modules. 

I'll add a test for option 2, that setting unchecked in the onChange action event unchecks. For now I'd recommend ensuring everything is properly data bound and updated on the change events. If you need to do something more advanced, you can use the 2nd parameter and manually execute the operation you need.

**Comment by cwilli34** [comment]
Same issue with the {{ui-radio}} component.  `checked=variable` does nothing, and in fact onChange is not necessary in my application, so I all I want is a mutable value.

**Comment by aaronbhansen** [comment]
@cwilli34 on 2.0 release nothing is mutated. You must use onChange to update your value.

**Comment by cwilli34** [comment]
Is there a way to update a variable in the template with onChange without calling an action?  An example maybe?  

I ended up just using `current=myVariable` to make this work.  Is that the correct way?

**Comment by aaronbhansen** [comment]
Yes, its in the [documentation](http://semantic-org.github.io/Semantic-UI-Ember/#/modules/radio)

`{{ui-radio name="fruit" label="Once a day" value="once-a-day" onChange=(action (mut fruit))}}`

**Comment by aaronbhansen** [comment]
@jfarlow anything else on this issue? Does option 2 or another way work for you?

**Comment by jfarlow** [comment]
I'm not particular of which option would be best.  Option 2 would work.  I just think the current situation is not ideal.  I don't mind having to use onChange, however I think the user's screen should always reflect the current state of the variable.

**Comment by aaronbhansen** [comment]
I agree, but can't think of a better way to handle it. The problem is two fold.

1. We have a state that is managed externally of ember, and when its changing its notifying you that something changed and you'll need to respond to it. 

2. Because of embers lifecycle hooks, we also don't get any events that something changed. In order for Ember to maintain performance, Ember isn't going to re-touch the checkbox component unless data binded to that component updates. Because of this round robin DDAU workflow, we have to assume that unless data changed to update the workflow the result is what you wanted. If we started to schedule things after render, we are breaking ember performance enhancements. 

I did think of some alternatives, you could disable or set the checkbox to read-only if you want to ensure it wouldn't change. You also don't get events on click. 

In the end, if you want events but also want to reset the checkbox's state, you'll have to handle it specifically. Its working around the known limitation of ember with an external plugin. You have to know that if you want something done outside of the normal workflow, you'll have to perform some extra work. 

If you think of any other ideas let me know and we can explore them

**Comment by cwilli34** [comment]
> Yes, its in the documentation

> {{ui-radio name="fruit" label="Once a day" value="once-a-day" onChange=(action (mut fruit))}}

Yes, that didn't work for me.  That was why I was wondering.  It didn't change the value at all.  Like I said, `current=myVariable` is all that would work.
