### ISSUE TITLE
Dropdown: Transition: Element is no longer attached to DOM. Unable to animate.

### ISSUE THREAD

**Issue by nojacko** [Semantic-Org/Semantic-UI-Ember#129]
Hey. Loving the library!

I'm using the ui-dropdown component to update a value of a query param. The query param causes the route the be refreshed and the component is destroyed during this. This causes the error...

`Transition: Element is no longer attached to DOM. Unable to animate.`

It's an easy fix my end. I just wrap my action in `Ember.run.next`.
```
actions: {
    selectId(item) {
        Ember.run.next(this, function() {
            var itemId = (item) ? item.get('id') : null;
            this.set('itemId', itemId);
        });
    }
},
```

I think it would be better for Semantic-UI-Ember to use Ember's run loop in the `_onChange` function. 

Any thoughts?

**Comment by aaronbhansen** [comment]
Do you have a loading route also by chance? We had a similar situation with a loading route and fixed it by changing loading.

**Comment by nojacko** [comment]
Yes, we've got a loading route. Just taken it out and I don't get the error since the main outlet isn't written over. However, we do need to get the loading routes.

**Comment by aaronbhansen** [comment]
We had the same issues, but tackled it differently. The problem with ember load routes is they completely overwrite the dom. To fix that we did two things.

One we created a loading template in the application route, or in a parent template

```
<div class="ui segment full-page-loading">
      <div class="ui active inverted dimmer">
        <div class="ui text loader">Loading</div>
      </div>
      <p></p>
</div>
```

With css like
```
.ui.segment.full-page-loading {
  display: none;
}
.loading-full .ui.segment.full-page-loading {
  display: block;
  width: 100%;
  height: 100%;
  position: absolute;
}
```

Then we created a route mixin that adds the classes on transitions to everything.

```
export default Ember.Mixin.create({
  activate() {
    this._super(...arguments);
    root = this.root();
    root.removeClass('loading-full');
  },
  root: function() {
    var element;
    element = window.$('html');
    if (!element.hasClass('root')) {
      element.addClass('root');
    }
    return element;
  },
  actions: {
    loading() {
      let root = this.root();
      root.addClass('loading-full');
      return true;
    },
    didTransition() {
      let root = this.root();
      root.removeClass('loading-full');
      return true;
    },
    error() {
      let root = this.root();
      root.removeClass('loading-full');
      return true;
    }
  },

  afterModel(/* model */) {
    this._super(...arguments);
    let root = this.root();
    root.removeClass('loading-full');
  }
});
```

Now every route has a loading state and you don't need to litter you app with loading routes. You could customize that, but I think the issue would happen to anything that replaced the dom while a 3rd party library was executing something.

**Comment by nojacko** [comment]
Thanks for the code.

While it does work, we prefer to stick to the out of the box Ember solution when we can. I'm sure many others will want to do the same.

The additional files are a pain, but they're all the same and we can add them during the build process. 

Since using the Ember run loop resolves this issue, I'd have thought it be more beneficial to implement this into the library as it prevent errors which result from standard Ember behaviour.

**Comment by aaronbhansen** [comment]
Sounds good, that was the idea with 2.0, you could implement things as you needed to. I mostly provided a solution we used instead of implementing the same loading screens over and over. 

The base mixin already actually uses the run queue as recommended in Ember to bind to the events from Semantic-UI https://github.com/Semantic-Org/Semantic-UI-Ember/blob/master/addon/mixins/base.js#L213

The problem with using the run queue too much is its more of a hack than a solution for everyone. It takes ember out of the DDAU cycle and now properties are scheduled to update rather than updating as they normally would. This same problem would happen with any third party library that has animations or scheduled changes after something is updated. 

As I also discussed on another ticket for updating the checkbox, one proposed solution was to use the run queue to check the state of the checkbox after it changed to see if the checked property changed or not. It's the same problem, you're working outside of DDUA.

I wish I had a better answer or solution, but I think will find that depending on how long duration of the animation takes on dropdown, the run queue might actually finish and execute setting the item and loading the page and causing the same issue you have today. Then whats the solution, to start Ember.run.later with a timeout to try and avoid animation issues. Or if semantic had a delayed animation or the animation duration changed, the run queue fix would stop working. 

In the end thats why we replaced the loading states with just css and html, so we didn't have the DOM replaced to avoid these issues. Anyway, if you have any other ideas or solutions I'm happy to look at them.
