### ISSUE TITLE
[Dropdown] Add loading indicator.

### ISSUE THREAD

**Issue by tabeth** [Semantic-Org/Semantic-UI-Ember#163]
It would be nice if `ui-dropdown` had native support for a loading indicator. Right now you can do it like so (I can create a PR for this particular implementation):

```
{{#ui-dropdown class="search selection"}}
  {{#if loading}}
    <div style="float: right" class="ui active inline mini loader"></div>
  {{/if}}
{{/ui-dropdown}}
```

However, a semantic-ui-ember implementation would be nice given that the [native](http://semantic-ui.com/modules/dropdown.html#loading) implementation doesn't work, ala:

```
{{#ui-dropdown class="search loading selection"}}
{{/ui-dropdown}}
```

**Comment by khornberg** [comment]
What about binding the loading attribute?

**Comment by aaronbhansen** [comment]
You should be able to add a class binding like @khornberg suggested. I've had a few times I've actually needed to load data within a dropdown. For that I extended the dropdown component and handled it outside of the Semantic api, since Ember needed to handle it differently. If you want to dive more into what you're looking for we can see if functionality exists today or if its something to expand on the library.
