### ISSUE TITLE
SemanticUI config issue in v2.0.1

### ISSUE THREAD

**Issue by shasiuk1** [Semantic-Org/Semantic-UI-Ember#180]
In version 2.0.1 semantic-ui.css is being added to vendor.css even if css import is set to false in config. Though in 2.0.0 it works as expected.

**Comment by aaronbhansen** [comment]
Thanks for reporting this. Looks like something must have changed when I updated the ember dependencies. I'll get a fix out in the next week for it. In the meantime if you put your settings in environment instead of ember-cli-build it will work

**Comment by rviney** [comment]
Yep it works fine in 2.0.1 if the `SemanticUI` config is placed `environment.js`. Is the plan to switch it back to be in `ember-cli-build.js` in the next release?

**Comment by rviney** [comment]
Actually I've since noticed that since this change Semantic UI's fonts and images aren't being included in a build. This was the commit that changed the behaviour: eb2a94207df2a5ceb698f87f9604921d22e05d65.

I'm unsure exactly what that commit was addressing, anyone know what "nested addons" are in this context?

Any chance of a 2.0.2 with this issue fixed?

**Comment by ScottShannon** [comment]
Using an addon inside of an addon.

**Comment by Bouke** [comment]
I'm running into the same issue. It would be great if the documentation would match the current implementation. So currently the settings need to go in `environment.js` instead of `ember-cli-build.js`.

**Comment by championswimmer** [comment]
please reopen if unresolved
