### ISSUE TITLE
Ember-based demo

### ISSUE THREAD

**Issue by lolmaus** [Semantic-Org/Semantic-UI-Ember#34]
It's hard to decide in favor of an Ember addon if the addon does not provide a live demo.

Please add one and publish it via `gh-pages`. Thank you. ^_^

**Comment by aaronbhansen** [comment]
What do you want demo'd? There is nothing different than what semantic already demos on their site semantic-ui.com

**Comment by lolmaus** [comment]
1. A list of currently implemented controls.
2. How they are bound to template properties.
3. How they are implemented under `tests/dummy/`.
4. How they are acceptance-tested under `tests/acceptance/`.

An ability to play with a live demo contributes to an addon's credibility a great deal.

**Comment by aaronbhansen** [comment]
1-2 are on the read.me. 3 sounds the same as 2, since everything except modal is template based, and modal is also on the read.me. 4 test are coming, but we haven't had time yet. Semantic UI Ember is a minimal wrapper over semantic ui. Currently this project is a side project of a side project. If you would like to see anything updated or implemented feel free to submit a pull request, we would love to have more community involvement.

**Comment by jlukic** [comment]
Thanks Aaron for all your hard work, it is truly appreciated.
