### ISSUE TITLE
Accordion: The method you called is not defined

### ISSUE THREAD

**Issue by cresg820** [Semantic-Org/Semantic-UI-Ember#54]
ember -v
    version: 1.13.8
    node: 4.1.1
    npm: 2.13.4
    os: linux x64`

Using accordion all seems to work but in console a get this error:

    DEBUG: -------------------------------
    DEBUG: Ember      : 2.0.0
    DEBUG: Ember Data : 2.0.0
    DEBUG: jQuery     : 1.11.3
    DEBUG: -------------------------------
    Ember Inspector Active
    Accordion: The method you called is not defined ["set"]

**Comment by nathanpalmer** [comment]
Thanks for the information. This is because we're calling "set" on the object itself to determine what properties within semantic on "settable." Some of the modules like Accordion don't support that.

@jlukic -- We're calling `.dropdown('set')` or `.accordion('set')` in this example which based on how the module system works will simply return the entire object of settable properties. This is so we can set up two-way bindings to get pushed back into semantic when they change in ember. It would be great if on modules such as Accordion it would have an empty hash. Thoughts?

**Comment by cresg820** [comment]
So this is not a real issue, right?
Thank you.

**Comment by nathanpalmer** [comment]
@cresg820 Right, it's not an issue. I would like to have the console message go away but otherwise the app should as expected

**Comment by cresg820** [comment]
Yes, it will be a good thing if error message will disappear.

Thanks for the support.
