### ISSUE TITLE
Make all the components follow reactive programming's principles

### ISSUE THREAD

**Issue by brendan-rius** [Semantic-Org/Semantic-UI-Ember#83]
To me, Ember's philosophy seems to put an emphasis on reactive programming: changing states instead of calling actions.

# Proposition
For example, it seems more Emberish to write something like:

```handlebars
{{ui-modal visible=isModalVisible}}
```

and make the modal appear/disappear when the variable `visible` changes, and the variable `visible` change when the user opens the modal or close it another way (by clicking outside it for example)

than it is to call it the way you do in [the README](https://github.com/Semantic-Org/Semantic-UI-Ember/blob/master/README.md):

```javascript
export default Ember.Controller.extend({
  actions: {
    openModal: function(name) {
      $('.ui.modal').modal('show');
    }
  }
});
```

It avoids making the controller aware of the DOM, and provides a beautiful way to have more features such as `is the modal visible right now?` (just read the variable `isModalVisible`).

Thus, the components should expose MORE properties corresponding to Semantic UI's behaviours, and internally change some of its properties depending on Semantic UI's events.

# Partial implementation example

You can find [here](https://gist.github.com/brendan-rius/3843cccad140edea5fe4) an example of a component I wrote to handle modals. It is not complete, because it just fills the need I had, but provides this kind of synchronisation between Ember properties and Semantic UI events:

and I can use it just like this:

HBS:
```handlebars
{{#my-modal isModalVisible=modalVisible}}
<h1>Title in the modal</h1>
{{/my-modal}}

<!-- the IF statement if just here to illustrate the fact that we can really
easily know if the modal is open by reading "modalVisible" -->
{{#if modalVisible}}
<a {{action "toggleModal"}}>Hide the modal</a>
{{else}}
<a {{action "toggleModal"}}>Show the modal</a>
{{/if}}
```

Controller:
```javascript
import Ember from 'ember';

export default Ember.Controller.extend({
    // "is/should the modal (be) currently visible"
    modalVisible: false,

    actions: {
        // Toggle modal visibility
        toggleModal: function () {
            // we can show or hide the modal, just by changing the property "modalVisible"
            this.set('modalVisible', !this.get('modalVisible'));
        }
    }
});
```

Note that here, if the user displays the modal and then click outside, `modalVisible` will know that the modal is now closed.

If you agree on this point I can try to implement this programming pattern for some Semantic UI's component in another branch.

**Comment by nathanpalmer** [comment]
Thanks for putting together this writeup @brendan-rius.

I've never been a fan of setting a property on your controller to control the invoking of the modal. I've seen it used in other examples and libraries. However, what I'd like to find is a way that's a bit closer to how ember's routing is setup that cleanly separates the logic and even transition into the modal.

Recently we've built a library that puts together some of the thoughts but I haven't had time to describe and document it and not sure whether we should merge it into this addon or create a separate one for it.

You can find the code here: https://github.com/unchartedcode/semantic-ui-ember-modal

Invoking modals is done through actions and fairly generically and allows you to pass arbitrary data into your modal.

```handlebars
<a {{action "open_modal" "project.edit"}}>Edit Project</a>
```

It requires adding an outlet to your `application.hbs`

```handlebars
{{outlet}}
{{outlet modal}}
```

and then once the user clicks it the modal component in the path `project.edit` will get created and data loaded into it.

Here is an example with data loaded

```handlebars
<div class="ui blue button" {{action "open_modal" "project/exports/generate-export" (hash name=export.name export_type=export.export_type format_type=export.format_type build_url=(action "build_export_url"))}}>
  <i class="cloud download icon"></i>
  Generate
</div>
```

It also handles proxying something of the common modal events into ember actions such as mentioned in #80. Though I'd like to do that in a cleaner more generic way (instead of just naming them explicitly.)

**Comment by aaronbhansen** [comment]
In addition to @nathanpalmer last comment, we will be changing to follow a data down actions up methodology for the next major release. This will allow you to directly tie into semantics own methods better. For the modal we might come up with a dual way to handle them. One way through routes, and then another through showing them in a template. From personal experience, some modals are part of a workflow that should be tied to routes, and some are more of notifications that could be on any template when triggered.

**Comment by aaronbhansen** [comment]
Starting on a 2.0 release branch tonight. Closing for this ticket for now. When 2.0 comes out and the changes are available, if you have things on that branch you would like to go over, open another ticket then. Thanks
